// Pythagorean letter-number chart
export const LETTER_VALUES: Record<string, number | string> = {
  a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9,
  j: 1, k: 2, l: 3, m: 4, n: 5, o: 6, p: 7, q: 8, r: 9,
  s: 1, t: 2, u: 3, v: 4, w: 5, x: 6, y: 7, z: 8,
  // Vietnamese vowels with diacritics -> base letter
  à: 'a', á: 'a', ả: 'a', ã: 'a', ạ: 'a',
  ă: 'a', ắ: 'a', ằ: 'a', ẳ: 'a', ẵ: 'a', ặ: 'a',
  â: 'a', ấ: 'a', ầ: 'a', ẩ: 'a', ẫ: 'a', ậ: 'a',
  è: 'e', é: 'e', ẻ: 'e', ẽ: 'e', ẹ: 'e',
  ê: 'e', ế: 'e', ề: 'e', ể: 'e', ễ: 'e', ệ: 'e',
  ì: 'i', í: 'i', ỉ: 'i', ĩ: 'i', ị: 'i',
  ò: 'o', ó: 'o', ỏ: 'o', õ: 'o', ọ: 'o',
  ô: 'o', ố: 'o', ồ: 'o', ổ: 'o', ỗ: 'o', ộ: 'o',
  ơ: 'o', ớ: 'o', ờ: 'o', ở: 'o', ỡ: 'o', ợ: 'o',
  ù: 'u', ú: 'u', ủ: 'u', ũ: 'u', ụ: 'u',
  ư: 'u', ứ: 'u', ừ: 'u', ử: 'u', ữ: 'u', ự: 'u',
  ỳ: 'y', ý: 'y', ỷ: 'y', ỹ: 'y', ỵ: 'y',
  đ: 'd',
};

export const VOWELS = new Set(['a', 'e', 'i', 'o', 'u', 'y']);

// ----- INTERPRETATION DATA -----

export interface NumberMeaning {
  name: string;
  nameEn: string;
  meaning: string;
  meaningEn: string;
  positive: string[];
  negative: string[];
  career: string;
  careerEn: string;
  lifePathMeaning: string;
  lifePathMeaningEn: string;
  destinyMeaning: string;
  destinyMeaningEn: string;
  soulUrgeMeaning: string;
  soulUrgeMeaningEn: string;
  personalityMeaning: string;
  personalityMeaningEn: string;
  birthDayMeaning: string;
  birthDayMeaningEn: string;
  maturityMeaning: string;
  maturityMeaningEn: string;
  balanceMeaning: string;
  balanceMeaningEn: string;
  challengeMeaning: string;
  challengeMeaningEn: string;
  pinnacleMeaning: string;
  pinnacleMeaningEn: string;
  periodMeaning: string;
  periodMeaningEn: string;
}

export const NUMBER_MEANINGS: Record<number, NumberMeaning> = {
  1: {
    name: 'Số 1 — Người tiên phong',
    nameEn: 'Number 1 — The Pioneer',
    meaning: 'Số 1 là biểu tượng của sự khởi đầu, độc lập, và khả năng lãnh đạo. Người mang năng lượng số 1 là người tiên phong, có ý chí mạnh mẽ và tinh thần tự lập cao.',
    meaningEn: 'Number 1 symbolizes beginning, independence, and leadership. People with number 1 energy are pioneers with strong willpower and high self-reliance.',
    positive: ['Độc lập', 'Sáng tạo', 'Quyết đoán', 'Dũng cảm', 'Lãnh đạo bẩm sinh'],
    negative: ['Ích kỷ', 'Độc đoán', 'Bảo thủ', 'Thiếu kiên nhẫn', 'Thích kiểm soát'],
    career: 'Phù hợp với các vai trò lãnh đạo, doanh nhân, quản lý, giám đốc điều hành, nhà sáng lập, hoặc bất kỳ công việc nào cho phép bạn tự chủ và sáng tạo.',
    careerEn: 'Suitable for leadership roles, entrepreneur, manager, CEO, founder, or any career that allows autonomy and creativity.',
    lifePathMeaning: 'Đường đời 1 — Hành trình của người tiên phong. Bạn đến với cuộc đời này để học cách đứng trên đôi chân của mình, phát triển sự tự tin và khả năng lãnh đạo. Bạn có tiềm năng trở thành người dẫn đầu, người mở đường cho những người khác.',
    lifePathMeaningEn: 'Life Path 1 — The journey of a pioneer. You came to this life to learn to stand on your own feet, develop confidence and leadership. You have the potential to be a leader and pathfinder for others.',
    destinyMeaning: 'Sứ mệnh 1 — Sứ mệnh của bạn là trở thành người tiên phong, dẫn dắt và truyền cảm hứng cho người khác bằng sự độc lập và sáng tạo của mình.',
    destinyMeaningEn: 'Destiny 1 — Your mission is to be a pioneer, leading and inspiring others through your independence and creativity.',
    soulUrgeMeaning: 'Linh hồn 1 — Tâm hồn bạn khao khát sự độc lập và tự do. Bạn muốn được là chính mình, không bị ràng buộc bởi người khác.',
    soulUrgeMeaningEn: 'Soul Urge 1 — Your soul craves independence and freedom. You want to be yourself without being bound by others.',
    personalityMeaning: 'Nhân cách 1 — Bạn toát ra vẻ ngoài mạnh mẽ, tự tin và quyết đoán. Người khác nhìn vào bạn và thấy một nhà lãnh đạo.',
    personalityMeaningEn: 'Personality 1 — You project a strong, confident, and decisive exterior. Others see a leader when they look at you.',
    birthDayMeaning: 'Sinh nhật 1 — Bạn sinh ra vào ngày của người lãnh đạo. Năng lượng tiên phong chảy mạnh trong bạn.',
    birthDayMeaningEn: 'Birthday 1 — You were born on the leader\'s day. Pioneer energy flows strongly in you.',
    maturityMeaning: 'Trưởng thành 1 — Khi trưởng thành, bạn sẽ phát huy tối đa khả năng lãnh đạo và sự tự tin của mình.',
    maturityMeaningEn: 'Maturity 1 — As you mature, you will maximize your leadership abilities and confidence.',
    balanceMeaning: 'Cân bằng 1 — Để cân bằng, bạn cần học cách kiên nhẫn và lắng nghe người khác, trong khi vẫn giữ vững tinh thần độc lập.',
    balanceMeaningEn: 'Balance 1 — To find balance, learn patience and listening to others while maintaining your independent spirit.',
    challengeMeaning: 'Thách thức số 1 — Bài học về sự tự tin và độc lập. Bạn cần vượt qua sự phụ thuộc vào người khác và tin vào chính mình.',
    challengeMeaningEn: 'Challenge of 1 — The lesson of confidence and independence. You need to overcome dependence on others and believe in yourself.',
    pinnacleMeaning: 'Đỉnh cao số 1 — Giai đoạn của sự khởi đầu mới, độc lập và thành công cá nhân. Đây là thời gian để bạn dẫn đầu.',
    pinnacleMeaningEn: 'Pinnacle of 1 — A period of new beginnings, independence, and personal success. This is your time to lead.',
    periodMeaning: 'Chu kỳ số 1 — Giai đoạn tập trung vào phát triển bản thân, xây dựng sự tự tin và khẳng định cá tính.',
    periodMeaningEn: 'Cycle of 1 — A period focused on self-development, building confidence, and asserting your individuality.',
  },
  2: {
    name: 'Số 2 — Người hòa giải',
    nameEn: 'Number 2 — The Diplomat',
    meaning: 'Số 2 đại diện cho sự hợp tác, nhạy cảm và ngoại giao. Người mang năng lượng số 2 là những người hòa giải tài ba, giàu lòng trắc ẩn và có khả năng kết nối sâu sắc.',
    meaningEn: 'Number 2 represents cooperation, sensitivity, and diplomacy. People with number 2 energy are skilled mediators, compassionate, and deeply connected.',
    positive: ['Hợp tác', 'Nhạy cảm', 'Kiên nhẫn', 'Khéo léo', 'Tận tụy'],
    negative: ['Thiếu quyết đoán', 'Quá nhạy cảm', 'Phụ thuộc', 'Dễ bị tổn thương', 'Ngại xung đột'],
    career: 'Phù hợp với các nghề liên quan đến hợp tác, tư vấn, tâm lý học, ngoại giao, hòa giải, chăm sóc sức khỏe, hoặc công việc theo nhóm.',
    careerEn: 'Suitable for careers in cooperation, counseling, psychology, diplomacy, mediation, healthcare, or team-oriented work.',
    lifePathMeaning: 'Đường đời 2 — Hành trình của người hòa giải. Bạn đến với cuộc đời để học về sự hợp tác, lòng kiên nhẫn và nghệ thuật xây dựng mối quan hệ. Bạn là cầu nối giữa mọi người.',
    lifePathMeaningEn: 'Life Path 2 — The journey of a mediator. You came to learn about cooperation, patience, and the art of building relationships. You are a bridge between people.',
    destinyMeaning: 'Sứ mệnh 2 — Sứ mệnh của bạn là mang lại sự hài hòa và cân bằng cho thế giới thông qua lòng trắc ẩn và khả năng ngoại giao.',
    destinyMeaningEn: 'Destiny 2 — Your mission is to bring harmony and balance to the world through compassion and diplomacy.',
    soulUrgeMeaning: 'Linh hồn 2 — Tâm hồn bạn khao khát sự hòa bình, tình yêu và kết nối sâu sắc với người khác.',
    soulUrgeMeaningEn: 'Soul Urge 2 — Your soul craves peace, love, and deep connection with others.',
    personalityMeaning: 'Nhân cách 2 — Bạn toát ra vẻ ngoài dịu dàng, dễ gần và đáng tin cậy. Người khác thấy bạn là người bạn đồng hành tuyệt vời.',
    personalityMeaningEn: 'Personality 2 — You project a gentle, approachable, and trustworthy exterior. Others see you as a wonderful companion.',
    birthDayMeaning: 'Sinh nhật 2 — Bạn sinh ra vào ngày của người hòa giải. Bạn có khả năng thiên bẩm trong việc kết nối và hợp tác.',
    birthDayMeaningEn: 'Birthday 2 — You were born on the diplomat\'s day. You have a natural gift for connection and cooperation.',
    maturityMeaning: 'Trưởng thành 2 — Khi trưởng thành, bạn sẽ phát triển khả năng ngoại giao và xây dựng mối quan hệ bền vững.',
    maturityMeaningEn: 'Maturity 2 — As you mature, you will develop your diplomatic skills and build lasting relationships.',
    balanceMeaning: 'Cân bằng 2 — Để cân bằng, bạn cần học cách đứng lên bảo vệ chính mình trong khi vẫn duy trì sự hài hòa với người khác.',
    balanceMeaningEn: 'Balance 2 — To find balance, learn to stand up for yourself while maintaining harmony with others.',
    challengeMeaning: 'Thách thức số 2 — Bài học về sự nhạy cảm và hợp tác. Bạn cần học cách cân bằng giữa nhu cầu của bản thân và người khác.',
    challengeMeaningEn: 'Challenge of 2 — The lesson of sensitivity and cooperation. Learn to balance your own needs with those of others.',
    pinnacleMeaning: 'Đỉnh cao số 2 — Giai đoạn của hợp tác, kết nối và phát triển mối quan hệ. Đây là thời gian để xây dựng cầu nối.',
    pinnacleMeaningEn: 'Pinnacle of 2 — A period of cooperation, connection, and relationship building. Time to build bridges.',
    periodMeaning: 'Chu kỳ số 2 — Giai đoạn tập trung vào các mối quan hệ, hợp tác và phát triển sự nhạy cảm.',
    periodMeaningEn: 'Cycle of 2 — A period focused on relationships, cooperation, and developing sensitivity.',
  },
  3: {
    name: 'Số 3 — Người sáng tạo',
    nameEn: 'Number 3 — The Creative',
    meaning: 'Số 3 là biểu tượng của sự sáng tạo, giao tiếp và niềm vui. Người mang năng lượng số 3 là người có tài năng nghệ thuật, hài hước và truyền cảm hứng.',
    meaningEn: 'Number 3 symbolizes creativity, communication, and joy. People with number 3 energy are artistic, humorous, and inspiring.',
    positive: ['Sáng tạo', 'Hài hước', 'Giao tiếp tốt', 'Lạc quan', 'Truyền cảm hứng'],
    negative: ['Phân tán', 'Thiếu kỷ luật', 'Kịch tính hóa', 'Dễ chán nản', 'Phù phiếm'],
    career: 'Phù hợp với các nghề sáng tạo như viết lách, nghệ thuật, thiết kế, diễn xuất, âm nhạc, truyền thông, hoặc bất kỳ công việc nào liên quan đến giao tiếp và biểu đạt.',
    careerEn: 'Suitable for creative careers like writing, art, design, acting, music, media, or any work involving communication and expression.',
    lifePathMeaning: 'Đường đời 3 — Hành trình của người sáng tạo. Bạn đến với cuộc đời để thể hiện bản thân, lan tỏa niềm vui và truyền cảm hứng cho người khác qua tài năng sáng tạo của mình.',
    lifePathMeaningEn: 'Life Path 3 — The journey of a creative. You came to express yourself, spread joy, and inspire others through your creative talents.',
    destinyMeaning: 'Sứ mệnh 3 — Sứ mệnh của bạn là sử dụng tài năng sáng tạo và giao tiếp để làm đẹp cho thế giới và kết nối mọi người.',
    destinyMeaningEn: 'Destiny 3 — Your mission is to use your creative and communication talents to beautify the world and connect people.',
    soulUrgeMeaning: 'Linh hồn 3 — Tâm hồn bạn khao khát được thể hiện, sáng tạo và mang lại niềm vui cho người khác.',
    soulUrgeMeaningEn: 'Soul Urge 3 — Your soul craves self-expression, creativity, and bringing joy to others.',
    personalityMeaning: 'Nhân cách 3 — Bạn toát ra vẻ ngoài vui vẻ, hài hước và đầy sức sống. Người khác thấy bạn là người thú vị và cuốn hút.',
    personalityMeaningEn: 'Personality 3 — You project a cheerful, humorous, and vibrant exterior. Others find you interesting and captivating.',
    birthDayMeaning: 'Sinh nhật 3 — Bạn sinh ra vào ngày của người sáng tạo. Năng lượng nghệ thuật chảy mạnh trong bạn.',
    birthDayMeaningEn: 'Birthday 3 — You were born on the creator\'s day. Artistic energy flows strongly in you.',
    maturityMeaning: 'Trưởng thành 3 — Khi trưởng thành, bạn sẽ phát huy tối đa khả năng sáng tạo và giao tiếp của mình.',
    maturityMeaningEn: 'Maturity 3 — As you mature, you will maximize your creativity and communication abilities.',
    balanceMeaning: 'Cân bằng 3 — Để cân bằng, bạn cần học cách tập trung và kỷ luật, trong khi vẫn nuôi dưỡng tinh thần sáng tạo.',
    balanceMeaningEn: 'Balance 3 — To find balance, learn focus and discipline while still nurturing your creative spirit.',
    challengeMeaning: 'Thách thức số 3 — Bài học về sự tập trung và kỷ luật. Bạn cần học cách kiểm soát năng lượng sáng tạo của mình.',
    challengeMeaningEn: 'Challenge of 3 — The lesson of focus and discipline. Learn to channel your creative energy.',
    pinnacleMeaning: 'Đỉnh cao số 3 — Giai đoạn của sáng tạo, niềm vui và thể hiện bản thân. Đây là thời gian để tỏa sáng.',
    pinnacleMeaningEn: 'Pinnacle of 3 — A period of creativity, joy, and self-expression. Time to shine.',
    periodMeaning: 'Chu kỳ số 3 — Giai đoạn tập trung vào phát triển sáng tạo, giao tiếp và niềm vui trong cuộc sống.',
    periodMeaningEn: 'Cycle of 3 — A period focused on developing creativity, communication, and joy in life.',
  },
  4: {
    name: 'Số 4 — Người xây dựng',
    nameEn: 'Number 4 — The Builder',
    meaning: 'Số 4 đại diện cho sự ổn định, kỷ luật và thực tế. Người mang năng lượng số 4 là người xây dựng vững chắc, chăm chỉ và đáng tin cậy.',
    meaningEn: 'Number 4 represents stability, discipline, and practicality. People with number 4 energy are solid builders, hardworking, and reliable.',
    positive: ['Chăm chỉ', 'Kỷ luật', 'Đáng tin cậy', 'Thực tế', 'Kiên trì'],
    negative: ['Cứng nhắc', 'Bảo thủ', 'Thiếu linh hoạt', 'Quá nghiêm túc', 'Hay lo lắng'],
    career: 'Phù hợp với các nghề như kỹ sư, kiến trúc sư, kế toán, quản lý dự án, xây dựng, nông nghiệp, hoặc bất kỳ công việc nào đòi hỏi sự tỉ mỉ và tổ chức.',
    careerEn: 'Suitable for careers as engineer, architect, accountant, project manager, construction, agriculture, or any work requiring precision and organization.',
    lifePathMeaning: 'Đường đời 4 — Hành trình của người xây dựng. Bạn đến với cuộc đời để xây dựng nền tảng vững chắc, tạo ra giá trị bền vững và học về kỷ luật.',
    lifePathMeaningEn: 'Life Path 4 — The journey of a builder. You came to build solid foundations, create lasting value, and learn discipline.',
    destinyMeaning: 'Sứ mệnh 4 — Sứ mệnh của bạn là tạo ra cấu trúc và ổn định cho thế giới, xây dựng những điều bền vững và có ý nghĩa.',
    destinyMeaningEn: 'Destiny 4 — Your mission is to bring structure and stability to the world, building lasting and meaningful things.',
    soulUrgeMeaning: 'Linh hồn 4 — Tâm hồn bạn khao khát sự ổn định, an toàn và một nền tảng vững chắc trong cuộc sống.',
    soulUrgeMeaningEn: 'Soul Urge 4 — Your soul craves stability, security, and a solid foundation in life.',
    personalityMeaning: 'Nhân cách 4 — Bạn toát ra vẻ ngoài nghiêm túc, đáng tin cậy và thực tế. Người khác thấy bạn là chỗ dựa vững chắc.',
    personalityMeaningEn: 'Personality 4 — You project a serious, reliable, and practical exterior. Others see you as a solid support.',
    birthDayMeaning: 'Sinh nhật 4 — Bạn sinh ra vào ngày của người xây dựng. Bạn có khả năng thiên bẩm trong việc tạo dựng nền tảng.',
    birthDayMeaningEn: 'Birthday 4 — You were born on the builder\'s day. You have a natural gift for creating foundations.',
    maturityMeaning: 'Trưởng thành 4 — Khi trưởng thành, bạn sẽ đạt được sự ổn định và thành công nhờ kỷ luật và chăm chỉ.',
    maturityMeaningEn: 'Maturity 4 — As you mature, you will achieve stability and success through discipline and hard work.',
    balanceMeaning: 'Cân bằng 4 — Để cân bằng, bạn cần học cách linh hoạt và mở lòng với những thay đổi, trong khi vẫn giữ nền tảng vững chắc.',
    balanceMeaningEn: 'Balance 4 — To find balance, learn flexibility and openness to change while maintaining a solid foundation.',
    challengeMeaning: 'Thách thức số 4 — Bài học về sự kiên nhẫn và kỷ luật. Bạn cần học cách xây dựng từ những điều nhỏ nhất.',
    challengeMeaningEn: 'Challenge of 4 — The lesson of patience and discipline. Learn to build from the smallest things.',
    pinnacleMeaning: 'Đỉnh cao số 4 — Giai đoạn của xây dựng, củng cố và tạo nền tảng vững chắc cho tương lai.',
    pinnacleMeaningEn: 'Pinnacle of 4 — A period of building, consolidation, and creating a solid foundation for the future.',
    periodMeaning: 'Chu kỳ số 4 — Giai đoạn tập trung vào công việc, kỷ luật và xây dựng sự ổn định.',
    periodMeaningEn: 'Cycle of 4 — A period focused on work, discipline, and building stability.',
  },
  5: {
    name: 'Số 5 — Người tự do',
    nameEn: 'Number 5 — The Free Spirit',
    meaning: 'Số 5 là biểu tượng của sự tự do, phiêu lưu và thay đổi. Người mang năng lượng số 5 là người yêu thích khám phá, linh hoạt và giàu năng lượng.',
    meaningEn: 'Number 5 symbolizes freedom, adventure, and change. People with number 5 energy love exploration, are flexible, and full of vitality.',
    positive: ['Tự do', 'Phiêu lưu', 'Linh hoạt', 'Đa năng', 'Giàu năng lượng'],
    negative: ['Thiếu trách nhiệm', 'Bồn chồn', 'Không ổn định', 'Quá đà', 'Thiếu cam kết'],
    career: 'Phù hợp với các nghề liên quan đến du lịch, truyền thông, báo chí, kinh doanh, bán hàng, tổ chức sự kiện, hoặc công việc có nhiều thay đổi và thử thách.',
    careerEn: 'Suitable for careers in travel, media, journalism, sales, business, event planning, or work with variety and challenges.',
    lifePathMeaning: 'Đường đời 5 — Hành trình của người tự do. Bạn đến với cuộc đời để trải nghiệm, khám phá và học về sự tự do đích thực. Cuộc đời bạn là một cuộc phiêu lưu.',
    lifePathMeaningEn: 'Life Path 5 — The journey of a free spirit. You came to experience, explore, and learn about true freedom. Your life is an adventure.',
    destinyMeaning: 'Sứ mệnh 5 — Sứ mệnh của bạn là mang lại sự thay đổi tích cực, khuyến khích người khác bước ra khỏi vùng an toàn và khám phá thế giới.',
    destinyMeaningEn: 'Destiny 5 — Your mission is to bring positive change, encourage others to step out of their comfort zone and explore.',
    soulUrgeMeaning: 'Linh hồn 5 — Tâm hồn bạn khao khát tự do, phiêu lưu và những trải nghiệm mới mẻ.',
    soulUrgeMeaningEn: 'Soul Urge 5 — Your soul craves freedom, adventure, and new experiences.',
    personalityMeaning: 'Nhân cách 5 — Bạn toát ra vẻ ngoài phóng khoáng, năng động và cuốn hút. Người khác thấy bạn thú vị và đầy bất ngờ.',
    personalityMeaningEn: 'Personality 5 — You project a free-spirited, dynamic, and captivating exterior. Others find you interesting and full of surprises.',
    birthDayMeaning: 'Sinh nhật 5 — Bạn sinh ra vào ngày của người tự do. Sự phiêu lưu nằm trong máu của bạn.',
    birthDayMeaningEn: 'Birthday 5 — You were born on the free spirit\'s day. Adventure runs in your blood.',
    maturityMeaning: 'Trưởng thành 5 — Khi trưởng thành, bạn sẽ cân bằng giữa khát khao tự do và trách nhiệm, đạt được sự viên mãn.',
    maturityMeaningEn: 'Maturity 5 — As you mature, you will balance the desire for freedom with responsibility, achieving fulfillment.',
    balanceMeaning: 'Cân bằng 5 — Để cân bằng, bạn cần học cách cam kết và có trách nhiệm, trong khi vẫn duy trì tinh thần tự do.',
    balanceMeaningEn: 'Balance 5 — To find balance, learn commitment and responsibility while maintaining your free spirit.',
    challengeMeaning: 'Thách thức số 5 — Bài học về sự tự do và trách nhiệm. Bạn cần học cách sử dụng tự do một cách khôn ngoan.',
    challengeMeaningEn: 'Challenge of 5 — The lesson of freedom and responsibility. Learn to use freedom wisely.',
    pinnacleMeaning: 'Đỉnh cao số 5 — Giai đoạn của thay đổi, tự do và mở rộng tầm nhìn. Đây là thời gian để khám phá.',
    pinnacleMeaningEn: 'Pinnacle of 5 — A period of change, freedom, and expanding horizons. Time to explore.',
    periodMeaning: 'Chu kỳ số 5 — Giai đoạn tập trung vào thay đổi, phiêu lưu và phát triển sự linh hoạt.',
    periodMeaningEn: 'Cycle of 5 — A period focused on change, adventure, and developing flexibility.',
  },
  6: {
    name: 'Số 6 — Người chăm sóc',
    nameEn: 'Number 6 — The Nurturer',
    meaning: 'Số 6 đại diện cho tình yêu thương, trách nhiệm và gia đình. Người mang năng lượng số 6 là người giàu lòng nhân ái, tận tụy và có trách nhiệm cao.',
    meaningEn: 'Number 6 represents love, responsibility, and family. People with number 6 energy are compassionate, devoted, and highly responsible.',
    positive: ['Yêu thương', 'Trách nhiệm', 'Tận tụy', 'Nhân ái', 'Bảo vệ'],
    negative: ['Can thiệp quá mức', 'Lo lắng thái quá', 'Hy sinh quá đà', 'Độc đoán', 'Tự cho mình đúng'],
    career: 'Phù hợp với các nghề như tư vấn, giảng dạy, chăm sóc sức khỏe, công tác xã hội, tâm lý học, hoặc bất kỳ công việc nào giúp đỡ và chăm sóc người khác.',
    careerEn: 'Suitable for careers in counseling, teaching, healthcare, social work, psychology, or any career helping and caring for others.',
    lifePathMeaning: 'Đường đời 6 — Hành trình của người chăm sóc. Bạn đến với cuộc đời để học về tình yêu thương vô điều kiện, trách nhiệm gia đình và sự phục vụ cộng đồng.',
    lifePathMeaningEn: 'Life Path 6 — The journey of a nurturer. You came to learn about unconditional love, family responsibility, and community service.',
    destinyMeaning: 'Sứ mệnh 6 — Sứ mệnh của bạn là chăm sóc, nuôi dưỡng và bảo vệ những người xung quanh, tạo ra một mái ấm yêu thương.',
    destinyMeaningEn: 'Destiny 6 — Your mission is to care for, nurture, and protect those around you, creating a loving home.',
    soulUrgeMeaning: 'Linh hồn 6 — Tâm hồn bạn khao khát tình yêu, gia đình và một mái ấm hạnh phúc.',
    soulUrgeMeaningEn: 'Soul Urge 6 — Your soul craves love, family, and a happy home.',
    personalityMeaning: 'Nhân cách 6 — Bạn toát ra vẻ ngoài ấm áp, đáng tin cậy và giàu tình cảm. Người khác thấy bạn như một mái ấm.',
    personalityMeaningEn: 'Personality 6 — You project a warm, reliable, and affectionate exterior. Others see you as a home.',
    birthDayMeaning: 'Sinh nhật 6 — Bạn sinh ra vào ngày của người chăm sóc. Tình yêu thương là bản năng của bạn.',
    birthDayMeaningEn: 'Birthday 6 — You were born on the nurturer\'s day. Love is your instinct.',
    maturityMeaning: 'Trưởng thành 6 — Khi trưởng thành, bạn sẽ tìm thấy niềm vui trong việc chăm sóc và xây dựng gia đình hạnh phúc.',
    maturityMeaningEn: 'Maturity 6 — As you mature, you will find joy in caring for others and building a happy family.',
    balanceMeaning: 'Cân bằng 6 — Để cân bằng, bạn cần học cách chăm sóc bản thân như cách bạn chăm sóc người khác.',
    balanceMeaningEn: 'Balance 6 — To find balance, learn to care for yourself the way you care for others.',
    challengeMeaning: 'Thách thức số 6 — Bài học về tình yêu thương và trách nhiệm. Bạn cần học cách yêu mà không kiểm soát.',
    challengeMeaningEn: 'Challenge of 6 — The lesson of love and responsibility. Learn to love without controlling.',
    pinnacleMeaning: 'Đỉnh cao số 6 — Giai đoạn của tình yêu, gia đình và trách nhiệm. Đây là thời gian để vun đắp tổ ấm.',
    pinnacleMeaningEn: 'Pinnacle of 6 — A period of love, family, and responsibility. Time to nurture your home.',
    periodMeaning: 'Chu kỳ số 6 — Giai đoạn tập trung vào gia đình, tình yêu và trách nhiệm.',
    periodMeaningEn: 'Cycle of 6 — A period focused on family, love, and responsibility.',
  },
  7: {
    name: 'Số 7 — Người tìm kiếm',
    nameEn: 'Number 7 — The Seeker',
    meaning: 'Số 7 là biểu tượng của tri thức, tâm linh và sự chiêm nghiệm. Người mang năng lượng số 7 là người thông thái, phân tích sâu sắc và có xu hướng tìm kiếm chân lý.',
    meaningEn: 'Number 7 symbolizes knowledge, spirituality, and contemplation. People with number 7 energy are wise, deeply analytical, and truth-seekers.',
    positive: ['Thông thái', 'Phân tích', 'Tâm linh', 'Chiêm nghiệm', 'Tìm tòi'],
    negative: ['Cô độc', 'Xa cách', 'Hoài nghi', 'Bí ẩn', 'Khó gần'],
    career: 'Phù hợp với các nghề như nhà khoa học, nghiên cứu, triết học, tâm lý học, công nghệ, phân tích dữ liệu, hoặc bất kỳ công việc nào đòi hỏi tư duy sâu sắc.',
    careerEn: 'Suitable for careers as scientist, researcher, philosopher, psychologist, technology, data analysis, or any work requiring deep thinking.',
    lifePathMeaning: 'Đường đời 7 — Hành trình của người tìm kiếm. Bạn đến với cuộc đời để tìm kiếm chân lý, khám phá tri thức và phát triển tâm linh. Bạn là người học hỏi suốt đời.',
    lifePathMeaningEn: 'Life Path 7 — The journey of a seeker. You came to search for truth, discover knowledge, and develop spiritually. You are a lifelong learner.',
    destinyMeaning: 'Sứ mệnh 7 — Sứ mệnh của bạn là khám phá và chia sẻ tri thức sâu sắc, giúp người khác nhìn thấy những điều ẩn giấu.',
    destinyMeaningEn: 'Destiny 7 — Your mission is to discover and share deep knowledge, helping others see hidden truths.',
    soulUrgeMeaning: 'Linh hồn 7 — Tâm hồn bạn khao khát sự hiểu biết sâu sắc, chân lý và kết nối tâm linh.',
    soulUrgeMeaningEn: 'Soul Urge 7 — Your soul craves deep understanding, truth, and spiritual connection.',
    personalityMeaning: 'Nhân cách 7 — Bạn toát ra vẻ ngoài bí ẩn, thông thái và có chiều sâu. Người khác thấy bạn là người đầy bí ẩn.',
    personalityMeaningEn: 'Personality 7 — You project a mysterious, wise, and profound exterior. Others see you as enigmatic.',
    birthDayMeaning: 'Sinh nhật 7 — Bạn sinh ra vào ngày của người tìm kiếm. Trí tuệ và sự chiêm nghiệm là bản chất của bạn.',
    birthDayMeaningEn: 'Birthday 7 — You were born on the seeker\'s day. Wisdom and contemplation are your essence.',
    maturityMeaning: 'Trưởng thành 7 — Khi trưởng thành, bạn sẽ đạt được sự thông thái và hiểu biết sâu sắc về cuộc đời.',
    maturityMeaningEn: 'Maturity 7 — As you mature, you will attain wisdom and deep understanding of life.',
    balanceMeaning: 'Cân bằng 7 — Để cân bằng, bạn cần học cách kết nối với thế giới xung quanh, không chỉ sống trong thế giới nội tâm.',
    balanceMeaningEn: 'Balance 7 — To find balance, learn to connect with the outside world, not just live in your inner world.',
    challengeMeaning: 'Thách thức số 7 — Bài học về sự tin tưởng và niềm tin. Bạn cần học cách tin vào những điều không thể thấy.',
    challengeMeaningEn: 'Challenge of 7 — The lesson of trust and faith. Learn to believe in things unseen.',
    pinnacleMeaning: 'Đỉnh cao số 7 — Giai đoạn của tri thức, tâm linh và phát triển nội tâm. Đây là thời gian để chiêm nghiệm.',
    pinnacleMeaningEn: 'Pinnacle of 7 — A period of knowledge, spirituality, and inner development. Time for contemplation.',
    periodMeaning: 'Chu kỳ số 7 — Giai đoạn tập trung vào phát triển tri thức, tâm linh và sự chiêm nghiệm.',
    periodMeaningEn: 'Cycle of 7 — A period focused on developing knowledge, spirituality, and contemplation.',
  },
  8: {
    name: 'Số 8 — Người quyền lực',
    nameEn: 'Number 8 — The Powerhouse',
    meaning: 'Số 8 đại diện cho quyền lực, thành công và vật chất. Người mang năng lượng số 8 là người có tham vọng lớn, khả năng lãnh đạo kinh doanh và tầm nhìn xa.',
    meaningEn: 'Number 8 represents power, success, and material wealth. People with number 8 energy are ambitious, business-savvy leaders with vision.',
    positive: ['Tham vọng', 'Quyết đoán', 'Có tầm nhìn', 'Tổ chức tốt', 'Giàu năng lực'],
    negative: ['Thích kiểm soát', 'Vật chất', 'Độc đoán', 'Căng thẳng', 'Thiếu cân bằng'],
    career: 'Phù hợp với các nghề như quản lý cấp cao, kinh doanh, tài chính, ngân hàng, bất động sản, đầu tư, hoặc lãnh đạo doanh nghiệp.',
    careerEn: 'Suitable for careers as executive, business owner, finance, banking, real estate, investing, or corporate leadership.',
    lifePathMeaning: 'Đường đời 8 — Hành trình của người quyền lực. Bạn đến với cuộc đời để học về quyền lực, thành công vật chất và sự cân bằng giữa vật chất và tinh thần.',
    lifePathMeaningEn: 'Life Path 8 — The journey of a powerhouse. You came to learn about power, material success, and the balance between material and spiritual.',
    destinyMeaning: 'Sứ mệnh 8 — Sứ mệnh của bạn là đạt được thành công lớn và sử dụng quyền lực của mình để tạo ra giá trị cho xã hội.',
    destinyMeaningEn: 'Destiny 8 — Your mission is to achieve great success and use your power to create value for society.',
    soulUrgeMeaning: 'Linh hồn 8 — Tâm hồn bạn khao khát thành công, quyền lực và sự công nhận từ xã hội.',
    soulUrgeMeaningEn: 'Soul Urge 8 — Your soul craves success, power, and recognition from society.',
    personalityMeaning: 'Nhân cách 8 — Bạn toát ra vẻ ngoài quyền lực, tự tin và có uy. Người khác thấy bạn là người đáng gờm.',
    personalityMeaningEn: 'Personality 8 — You project a powerful, confident, and authoritative exterior. Others see you as formidable.',
    birthDayMeaning: 'Sinh nhật 8 — Bạn sinh ra vào ngày của người quyền lực. Tham vọng và khả năng lãnh đạo là bản chất của bạn.',
    birthDayMeaningEn: 'Birthday 8 — You were born on the powerhouse\'s day. Ambition and leadership are your essence.',
    maturityMeaning: 'Trưởng thành 8 — Khi trưởng thành, bạn sẽ đạt được đỉnh cao sự nghiệp và thành công vật chất.',
    maturityMeaningEn: 'Maturity 8 — As you mature, you will reach career heights and material success.',
    balanceMeaning: 'Cân bằng 8 — Để cân bằng, bạn cần học cách quan tâm đến giá trị tinh thần, không chỉ vật chất.',
    balanceMeaningEn: 'Balance 8 — To find balance, learn to value spiritual wealth, not just material.',
    challengeMeaning: 'Thách thức số 8 — Bài học về sự cân bằng và chính trực. Bạn cần học cách sử dụng quyền lực một cách có trách nhiệm.',
    challengeMeaningEn: 'Challenge of 8 — The lesson of balance and integrity. Learn to use power responsibly.',
    pinnacleMeaning: 'Đỉnh cao số 8 — Giai đoạn của thành công, quyền lực và đạt được mục tiêu lớn. Đây là thời gian để gặt hái.',
    pinnacleMeaningEn: 'Pinnacle of 8 — A period of success, power, and achieving big goals. Time to reap rewards.',
    periodMeaning: 'Chu kỳ số 8 — Giai đoạn tập trung vào sự nghiệp, quyền lực và thành công vật chất.',
    periodMeaningEn: 'Cycle of 8 — A period focused on career, power, and material success.',
  },
  9: {
    name: 'Số 9 — Người nhân đạo',
    nameEn: 'Number 9 — The Humanitarian',
    meaning: 'Số 9 là biểu tượng của lòng nhân đạo, trí tuệ bao quát và sự hoàn thiện. Người mang năng lượng số 9 là người có tầm nhìn rộng, giàu lòng vị tha và khát khao cống hiến.',
    meaningEn: 'Number 9 symbolizes humanitarianism, universal wisdom, and completion. People with number 9 energy have broad vision, compassion, and desire to serve.',
    positive: ['Nhân đạo', 'Vị tha', 'Sáng suốt', 'Có tầm nhìn', 'Truyền cảm hứng'],
    negative: ['Xa rời thực tế', 'Quá lý tưởng', 'Hy sinh quá mức', 'Dễ tổn thương', 'Khó buông bỏ'],
    career: 'Phù hợp với các nghề như tổ chức phi lợi nhuận, hoạt động xã hội, giáo dục, nghệ thuật, tư vấn tâm lý, hoặc các công việc mang tính nhân văn và cộng đồng.',
    careerEn: 'Suitable for careers in non-profit, social activism, education, arts, counseling, or humanitarian and community work.',
    lifePathMeaning: 'Đường đời 9 — Hành trình của người nhân đạo. Bạn đến với cuộc đời để phục vụ nhân loại, thể hiện lòng vị tha và hoàn thiện bản thân qua việc cho đi.',
    lifePathMeaningEn: 'Life Path 9 — The journey of a humanitarian. You came to serve humanity, express compassion, and find completion through giving.',
    destinyMeaning: 'Sứ mệnh 9 — Sứ mệnh của bạn là làm cho thế giới tốt đẹp hơn, truyền cảm hứng và giúp đỡ những người kém may mắn.',
    destinyMeaningEn: 'Destiny 9 — Your mission is to make the world better, inspire others, and help the less fortunate.',
    soulUrgeMeaning: 'Linh hồn 9 — Tâm hồn bạn khao khát được cống hiến, giúp đỡ người khác và làm điều lớn lao cho nhân loại.',
    soulUrgeMeaningEn: 'Soul Urge 9 — Your soul craves to contribute, help others, and do something great for humanity.',
    personalityMeaning: 'Nhân cách 9 — Bạn toát ra vẻ ngoài rộng lượng, thông thái và đầy cảm hứng. Người khác thấy bạn là người đáng kính trọng.',
    personalityMeaningEn: 'Personality 9 — You project a generous, wise, and inspiring exterior. Others see you as admirable.',
    birthDayMeaning: 'Sinh nhật 9 — Bạn sinh ra vào ngày của người nhân đạo. Lòng vị tha là bản chất của bạn.',
    birthDayMeaningEn: 'Birthday 9 — You were born on the humanitarian\'s day. Compassion is your essence.',
    maturityMeaning: 'Trưởng thành 9 — Khi trưởng thành, bạn sẽ tìm thấy ý nghĩa cuộc sống qua việc phục vụ và cống hiến cho cộng đồng.',
    maturityMeaningEn: 'Maturity 9 — As you mature, you will find life meaning through service and contribution to the community.',
    balanceMeaning: 'Cân bằng 9 — Để cân bằng, bạn cần học cách chăm sóc bản thân trong khi vẫn cống hiến cho người khác.',
    balanceMeaningEn: 'Balance 9 — To find balance, learn to care for yourself while still serving others.',
    challengeMeaning: 'Thách thức số 9 — Bài học về sự buông bỏ và lòng vị tha. Bạn cần học cách cho đi mà không mong nhận lại.',
    challengeMeaningEn: 'Challenge of 9 — The lesson of letting go and compassion. Learn to give without expecting return.',
    pinnacleMeaning: 'Đỉnh cao số 9 — Giai đoạn của hoàn thiện, nhân đạo và phục vụ cộng đồng. Đây là thời gian để cho đi.',
    pinnacleMeaningEn: 'Pinnacle of 9 — A period of completion, humanitarianism, and community service. Time to give back.',
    periodMeaning: 'Chu kỳ số 9 — Giai đoạn tập trung vào nhân đạo, phục vụ và hoàn thiện bản thân.',
    periodMeaningEn: 'Cycle of 9 — A period focused on humanitarianism, service, and self-completion.',
  },
};

// Master numbers
export const MASTER_NUMBER_MEANINGS: Record<number, Partial<NumberMeaning>> = {
  11: {
    name: 'Số 11 — Người giác ngộ (Master Number)',
    nameEn: 'Number 11 — The Illuminator (Master Number)',
    meaning: 'Số 11 là master number đầu tiên, mang năng lượng tâm linh mạnh mẽ. Người mang số 11 có trực giác siêu phàm, khả năng ngoại cảm và tầm nhìn tâm linh sâu sắc.',
    meaningEn: 'Number 11 is the first master number, carrying powerful spiritual energy. People with number 11 have extraordinary intuition, psychic ability, and deep spiritual vision.',
    positive: ['Trực giác siêu phàm', 'Tâm linh', 'Cảm hứng', 'Sáng tạo', 'Giác ngộ'],
    negative: ['Căng thẳng thần kinh', 'Bất an', 'Quá nhạy cảm', 'Sống ảo tưởng', 'Kiệt sức'],
    career: 'Phù hợp với các nghề như nhà lãnh đạo tinh thần, diễn giả truyền cảm hứng, nghệ sĩ, nhà tâm lý học, hoặc bất kỳ công việc nào truyền cảm hứng và thức tỉnh người khác.',
    careerEn: 'Suitable for careers as spiritual leader, inspirational speaker, artist, psychologist, or any work inspiring and awakening others.',
    lifePathMeaning: 'Đường đời 11 — Hành trình giác ngộ. Bạn là một linh hồn già cả với sứ mệnh tâm linh đặc biệt. Bạn đến để mang ánh sáng tri thức và cảm hứng cho nhân loại. Trực giác của bạn là kim chỉ nam.',
    lifePathMeaningEn: 'Life Path 11 — The enlightenment journey. You are an old soul with a special spiritual mission. You came to bring the light of knowledge and inspiration to humanity. Your intuition is your compass.',
    soulUrgeMeaning: 'Linh hồn 11 — Tâm hồn bạn khao khát sự giác ngộ tâm linh và khát khao được truyền cảm hứng cho người khác ở mức độ sâu sắc nhất.',
    soulUrgeMeaningEn: 'Soul Urge 11 — Your soul craves spiritual enlightenment and a deep desire to inspire others at the deepest level.',
  },
  22: {
    name: 'Số 22 — Người kiến tạo (Master Number)',
    nameEn: 'Number 22 — The Master Builder (Master Number)',
    meaning: 'Số 22 là master number mạnh nhất, kết hợp tầm nhìn tâm linh của số 11 với khả năng xây dựng thực tế của số 4. Người mang số 22 có khả năng biến ước mơ lớn nhất thành hiện thực.',
    meaningEn: 'Number 22 is the most powerful master number, combining the spiritual vision of 11 with the practical building ability of 4. People with number 22 can turn the biggest dreams into reality.',
    positive: ['Tầm nhìn lớn', 'Kiến tạo vĩ đại', 'Khả năng tổ chức', 'Thực tế', 'Có sức ảnh hưởng'],
    negative: ['Áp lực quá lớn', 'Tham vọng quá mức', 'Căng thẳng', 'Thiếu kiên nhẫn', 'Quá tải'],
    career: 'Phù hợp với các nghề như kiến trúc sư quy mô lớn, nhà lãnh đạo toàn cầu, nhà phát minh, doanh nhân tầm cỡ thế giới.',
    careerEn: 'Suitable for careers as large-scale architect, global leader, inventor, world-class entrepreneur.',
    lifePathMeaning: 'Đường đời 22 — Hành trình của người kiến tạo vĩ đại. Bạn được ban cho khả năng đặc biệt để biến những giấc mơ lớn nhất thành hiện thực. Bạn có thể xây dựng những điều có tầm ảnh hưởng đến toàn nhân loại.',
    lifePathMeaningEn: 'Life Path 22 — The journey of the master builder. You are gifted with the special ability to turn the biggest dreams into reality. You can build things of global impact.',
    soulUrgeMeaning: 'Linh hồn 22 — Tâm hồn bạn khao khát tạo ra những điều vĩ đại, có tầm ảnh hưởng lâu dài đến thế giới.',
    soulUrgeMeaningEn: 'Soul Urge 22 — Your soul craves to create great things with lasting impact on the world.',
  },
  33: {
    name: 'Số 33 — Người chữa lành (Master Number)',
    nameEn: 'Number 33 — The Master Teacher (Master Number)',
    meaning: 'Số 33 là master number của tình yêu thương vô điều kiện và sự chữa lành. Người mang số 33 có khả năng yêu thương và chữa lành ở mức độ sâu sắc nhất.',
    meaningEn: 'Number 33 is the master number of unconditional love and healing. People with number 33 can love and heal at the deepest level.',
    positive: ['Yêu thương vô điều kiện', 'Chữa lành', 'Dạy dỗ', 'Từ bi', 'Hy sinh'],
    negative: ['Quá tải cảm xúc', 'Hy sinh quá mức', 'Dễ bị lợi dụng', 'Căng thẳng'],
    career: 'Phù hợp với các nghề như giáo viên tâm linh, người chữa lành, nhà hoạt động nhân đạo toàn cầu.',
    careerEn: 'Suitable for careers as spiritual teacher, healer, global humanitarian activist.',
    lifePathMeaning: 'Đường đời 33 — Hành trình của người chữa lành và dạy dỗ. Bạn đến với cuộc đời để yêu thương vô điều kiện và nâng đỡ tâm hồn người khác. Tình yêu của bạn có sức mạnh chữa lành.',
    lifePathMeaningEn: 'Life Path 33 — The journey of the healer and teacher. You came to love unconditionally and uplift others\' souls. Your love has healing power.',
    soulUrgeMeaning: 'Linh hồn 33 — Tâm hồn bạn khao khát được yêu thương và chữa lành cho tất cả mọi người.',
    soulUrgeMeaningEn: 'Soul Urge 33 — Your soul craves to love and heal all people.',
  },
};

// Challenge interpretations for special numbers
export const CHALLENGE_MEANINGS: Record<number, { meaning: string; meaningEn: string }> = {
  0: { meaning: 'Không có thách thức đặc biệt — Bạn có khả năng vượt qua mọi trở ngại một cách tự nhiên. Thách thức 0 cho thấy bạn có nhiều lựa chọn và tự do trong cuộc sống.', meaningEn: 'No special challenge — You can naturally overcome any obstacle. Challenge 0 indicates many choices and freedom in life.' },
};

// Period cycle meanings
export const PERIOD_MEANINGS: Record<number, { meaning: string; meaningEn: string }> = {
  1: { meaning: 'Giai đoạn độc lập — Phát triển cá tính riêng, học cách đứng trên đôi chân của mình và lãnh đạo.', meaningEn: 'Period of independence — Develop your individuality, learn to stand on your own feet and lead.' },
  2: { meaning: 'Giai đoạn hợp tác — Học về các mối quan hệ, kiên nhẫn, và làm việc với người khác.', meaningEn: 'Period of cooperation — Learn about relationships, patience, and working with others.' },
  3: { meaning: 'Giai đoạn sáng tạo — Thể hiện bản thân, phát triển tài năng nghệ thuật và giao tiếp.', meaningEn: 'Period of creativity — Self-expression, develop artistic talents and communication.' },
  4: { meaning: 'Giai đoạn xây dựng — Làm việc chăm chỉ, xây dựng nền tảng vững chắc và kỷ luật.', meaningEn: 'Period of building — Work hard, build solid foundations and discipline.' },
  5: { meaning: 'Giai đoạn thay đổi — Trải nghiệm tự do, phiêu lưu và những thay đổi lớn.', meaningEn: 'Period of change — Experience freedom, adventure and major changes.' },
  6: { meaning: 'Giai đoạn trách nhiệm — Tập trung vào gia đình, tình yêu và trách nhiệm với cộng đồng.', meaningEn: 'Period of responsibility — Focus on family, love and responsibility to community.' },
  7: { meaning: 'Giai đoạn chiêm nghiệm — Phát triển tâm linh, học hỏi và tìm kiếm tri thức sâu sắc.', meaningEn: 'Period of contemplation — Spiritual development, learning and seeking deep knowledge.' },
  8: { meaning: 'Giai đoạn thành công — Gặt hái thành quả, phát triển sự nghiệp và quyền lực.', meaningEn: 'Period of success — Reap rewards, career development and power.' },
  9: { meaning: 'Giai đoạn hoàn thiện — Kết thúc một chu kỳ, phục vụ cộng đồng và chuẩn bị cho khởi đầu mới.', meaningEn: 'Period of completion — End of a cycle, serve community and prepare for new beginnings.' },
};

export const CORNERSTONE_MEANINGS: Record<number, string> = {
  1: 'Bạn có xu hướng độc lập và quyết đoán trong cách tiếp cận cuộc sống.',
  2: 'Bạn tiếp cận cuộc sống một cách nhạy cảm và hợp tác.',
  3: 'Bạn tiếp cận cuộc sống với sự sáng tạo và niềm vui.',
  4: 'Bạn tiếp cận cuộc sống một cách thực tế và có tổ chức.',
  5: 'Bạn tiếp cận cuộc sống với tinh thần phiêu lưu và khát khao tự do.',
  6: 'Bạn tiếp cận cuộc sống với trách nhiệm và tình yêu thương.',
  7: 'Bạn tiếp cận cuộc sống với sự chiêm nghiệm và tìm kiếm tri thức.',
  8: 'Bạn tiếp cận cuộc sống với tham vọng và quyết tâm thành công.',
  9: 'Bạn tiếp cận cuộc sống với lòng nhân đạo và tầm nhìn rộng.',
};
