// Chiêm tinh học — Interpretations & Constants
import type { AstrologyResult } from './types';

// ----- 12 CUNG HOÀNG ĐẠO -----
export const ZODIAC = [
  {
    vi: "Bạch Dương", en: "Aries", symbol: "♈", element: "Lửa", quality: "Thống lĩnh", ruler: "Sao Hỏa",
    start: 0,
    positive: ["Dũng cảm", "Nhiệt huyết", "Tiên phong", "Tự tin", "Năng động"],
    negative: ["Bốc đồng", "Nóng nảy", "Thiếu kiên nhẫn", "Hấp tấp"],
    meaning: "Bạch Dương là cung đầu tiên, tượng trưng cho sự khởi đầu và năng lượng tiên phong. Người thuộc cung Bạch Dương dũng cảm, quyết đoán và luôn sẵn sàng đương đầu với thử thách.",
    meaningEn: "Aries is the first sign, symbolizing new beginnings and pioneering energy. Arians are brave, decisive and always ready to face challenges.",
    career: "Phù hợp với lãnh đạo, kinh doanh, thể thao, quân đội, kỹ thuật.",
    love: "Trong tình yêu, Bạch Dương mãnh liệt, chân thành và thích chinh phục. Cần học cách kiên nhẫn và lắng nghe.",
  },
  {
    vi: "Kim Ngưu", en: "Taurus", symbol: "♉", element: "Đất", quality: "Cố định", ruler: "Sao Kim",
    start: 30,
    positive: ["Kiên định", "Đáng tin", "Kiên nhẫn", "Thực tế", "Trung thành"],
    negative: ["Bảo thủ", "Lười biếng", "Sở hữu", "Cứng đầu"],
    meaning: "Kim Ngưu tượng trưng cho sự ổn định và bền bỉ. Người thuộc cung Kim Ngưu thực tế, đáng tin cậy và có gu thẩm mỹ tinh tế.",
    meaningEn: "Taurus symbolizes stability and endurance. Taureans are practical, reliable and have refined aesthetic taste.",
    career: "Phù hợp với tài chính, bất động sản, nghệ thuật, ẩm thực, nông nghiệp.",
    love: "Trong tình yêu, Kim Ngưu chung thủy, ấm áp và thích sự ổn định. Ghét sự thay đổi đột ngột.",
  },
  {
    vi: "Song Tử", en: "Gemini", symbol: "♊", element: "Khí", quality: "Linh hoạt", ruler: "Sao Thủy",
    start: 60,
    positive: ["Thông minh", "Linh hoạt", "Giao tiếp tốt", "Hài hước", "Tò mò"],
    negative: ["Hay thay đổi", "Hời hợt", "Lưỡng lự", "Bồn chồn"],
    meaning: "Song Tử tượng trưng cho giao tiếp và tri thức. Người thuộc cung Song Tử thông minh, nhanh nhẹn và có khả năng thích ứng cao.",
    meaningEn: "Gemini symbolizes communication and intellect. Geminis are intelligent, quick-witted and highly adaptable.",
    career: "Phù hợp với truyền thông, báo chí, giảng dạy, công nghệ, du lịch.",
    love: "Trong tình yêu, Song Tử vui vẻ, thú vị và thích sự mới mẻ. Cần một người bạn đời đồng hành về trí tuệ.",
  },
  {
    vi: "Cự Giải", en: "Cancer", symbol: "♋", element: "Nước", quality: "Thống lĩnh", ruler: "Mặt Trăng",
    start: 90,
    positive: ["Ấm áp", "Trực giác tốt", "Bảo vệ", "Tận tụy", "Giàu cảm xúc"],
    negative: ["Nhạy cảm quá", "Ủy mị", "Phụ thuộc", "Thất thường"],
    meaning: "Cự Giải tượng trưng cho gia đình và cảm xúc. Người thuộc cung Cự Giải ấm áp, giàu lòng trắc ẩn và gắn bó với gia đình.",
    meaningEn: "Cancer symbolizes family and emotions. Cancerians are warm, compassionate and family-oriented.",
    career: "Phù hợp với bất động sản, ẩm thực, giáo dục, tâm lý, chăm sóc sức khỏe.",
    love: "Trong tình yêu, Cự Giải sâu sắc, chung thủy và hết lòng vì người mình yêu. Rất coi trọng gia đình.",
  },
  {
    vi: "Sư Tử", en: "Leo", symbol: "♌", element: "Lửa", quality: "Cố định", ruler: "Mặt Trời",
    start: 120,
    positive: ["Tự tin", "Hào phóng", "Sáng tạo", "Lãnh đạo", "Nhiệt tình"],
    negative: ["Kiêu ngạo", "Thích kiểm soát", "Ích kỷ", "Kịch tính"],
    meaning: "Sư Tử tượng trưng cho quyền lực và sự sáng tạo. Người thuộc cung Sư Tử tự tin, hào phóng và có khả năng lãnh đạo thiên bẩm.",
    meaningEn: "Leo symbolizes power and creativity. Leos are confident, generous and natural leaders.",
    career: "Phù hợp với lãnh đạo, giải trí, nghệ thuật, thiết kế, diễn xuất.",
    love: "Trong tình yêu, Sư Tử mãnh liệt, lãng mạn và hào phóng. Thích được tôn trọng và ngưỡng mộ.",
  },
  {
    vi: "Xử Nữ", en: "Virgo", symbol: "♍", element: "Đất", quality: "Linh hoạt", ruler: "Sao Thủy",
    start: 150,
    positive: ["Tỉ mỉ", "Phân tích", "Thông minh", "Cầu toàn", "Chăm chỉ"],
    negative: ["Khó tính", "Lo lắng", "Chỉ trích", "Cầu toàn quá mức"],
    meaning: "Xử Nữ tượng trưng cho sự hoàn hảo và phục vụ. Người thuộc cung Xử Nữ tỉ mỉ, thông minh và có tinh thần trách nhiệm cao.",
    meaningEn: "Virgo symbolizes perfection and service. Virgos are meticulous, intelligent and highly responsible.",
    career: "Phù hợp với y tế, giáo dục, nghiên cứu, kế toán, công nghệ.",
    love: "Trong tình yêu, Xử Nữ chân thành, chu đáo và thể hiện tình cảm qua hành động. Cần học cách thư giãn.",
  },
  {
    vi: "Thiên Bình", en: "Libra", symbol: "♎", element: "Khí", quality: "Thống lĩnh", ruler: "Sao Kim",
    start: 180,
    positive: ["Khéo léo", "Công bằng", "Quyến rũ", "Hợp tác", "Thanh lịch"],
    negative: ["Do dự", "Phụ thuộc", "Tránh xung đột", "Hời hợt"],
    meaning: "Thiên Bình tượng trưng cho sự cân bằng và hài hòa. Người thuộc cung Thiên Bình khéo léo, công bằng và có gu thẩm mỹ tinh tế.",
    meaningEn: "Libra symbolizes balance and harmony. Librans are diplomatic, fair and have refined taste.",
    career: "Phù hợp với luật pháp, ngoại giao, thiết kế, tư vấn, nghệ thuật.",
    love: "Trong tình yêu, Thiên Bình lãng mạn, quyến rũ và tìm kiếm sự hài hòa. Ghét sự xung đột và căng thẳng.",
  },
  {
    vi: "Bọ Cạp", en: "Scorpio", symbol: "♏", element: "Nước", quality: "Cố định", ruler: "Diêm Vương",
    start: 210,
    positive: ["Sâu sắc", "Quyết tâm", "Trực giác mạnh", "Trung thành", "Bí ẩn"],
    negative: ["Ghen tuông", "Thích kiểm soát", "Bí mật", "Cực đoan"],
    meaning: "Bọ Cạp tượng trưng cho sự biến đổi và chiều sâu. Người thuộc cung Bọ Cạp sâu sắc, quyết tâm và có trực giác mạnh mẽ.",
    meaningEn: "Scorpio symbolizes transformation and depth. Scorpios are intense, determined and highly intuitive.",
    career: "Phù hợp với nghiên cứu, tâm lý, điều tra, phẫu thuật, tài chính.",
    love: "Trong tình yêu, Bọ Cạp mãnh liệt, chung thủy và sâu sắc. Yêu hết mình và đòi hỏi sự tương xứng.",
  },
  {
    vi: "Nhân Mã", en: "Sagittarius", symbol: "♐", element: "Lửa", quality: "Linh hoạt", ruler: "Sao Mộc",
    start: 240,
    positive: ["Lạc quan", "Phiêu lưu", "Trung thực", "Hài hước", "Tự do"],
    negative: ["Thiếu tế nhị", "Bồn chồn", "Cam kết kém", "Quá lạc quan"],
    meaning: "Nhân Mã tượng trưng cho sự khám phá và triết lý. Người thuộc cung Nhân Mã lạc quan, yêu tự do và có tinh thần phiêu lưu.",
    meaningEn: "Sagittarius symbolizes exploration and philosophy. Sagittarians are optimistic, freedom-loving and adventurous.",
    career: "Phù hợp với du lịch, giáo dục, triết học, thể thao, truyền thông.",
    love: "Trong tình yêu, Nhân Mã chân thành, vui vẻ và cần không gian riêng. Ghét sự ràng buộc quá mức.",
  },
  {
    vi: "Ma Kết", en: "Capricorn", symbol: "♑", element: "Đất", quality: "Thống lĩnh", ruler: "Sao Thổ",
    start: 270,
    positive: ["Tham vọng", "Kỷ luật", "Kiên nhẫn", "Trách nhiệm", "Thực tế"],
    negative: ["Lạnh lùng", "Bi quan", "Cứng nhắc", "Vật chất"],
    meaning: "Ma Kết tượng trưng cho thành công và trách nhiệm. Người thuộc cung Ma Kết tham vọng, kỷ luật và có tinh thần trách nhiệm cao.",
    meaningEn: "Capricorn symbolizes success and responsibility. Capricorns are ambitious, disciplined and highly responsible.",
    career: "Phù hợp với quản lý, tài chính, kiến trúc, chính trị, kinh doanh.",
    love: "Trong tình yêu, Ma Kết chân thành, cam kết và thể hiện tình cảm qua hành động. Cần học cách thể hiện cảm xúc.",
  },
  {
    vi: "Bảo Bình", en: "Aquarius", symbol: "♒", element: "Khí", quality: "Cố định", ruler: "Sao Thiên Vương",
    start: 300,
    positive: ["Sáng tạo", "Nhân đạo", "Độc lập", "Tiến bộ", "Thông minh"],
    negative: ["Xa cách", "Nổi loạn", "Khó đoán", "Bướng bỉnh"],
    meaning: "Bảo Bình tượng trưng cho sự đổi mới và nhân đạo. Người thuộc cung Bảo Bình sáng tạo, độc lập và có tầm nhìn xa.",
    meaningEn: "Aquarius symbolizes innovation and humanity. Aquarians are creative, independent and forward-thinking.",
    career: "Phù hợp với công nghệ, nghiên cứu, nhân quyền, khoa học, sáng tạo.",
    love: "Trong tình yêu, Bảo Bình độc đáo, trung thành và coi trọng tình bạn. Cần không gian riêng và sự tự do.",
  },
  {
    vi: "Song Ngư", en: "Pisces", symbol: "♓", element: "Nước", quality: "Linh hoạt", ruler: "Sao Hải Vương",
    start: 330,
    positive: ["Nhân từ", "Sáng tạo", "Trực giác", "Vị tha", "Mơ mộng"],
    negative: ["Ảo tưởng", "Nhạy cảm quá", "Thiếu thực tế", "Hy sinh"],
    meaning: "Song Ngư tượng trưng cho giấc mơ và tâm linh. Người thuộc cung Song Ngư nhân từ, sáng tạo và giàu lòng trắc ẩn.",
    meaningEn: "Pisces symbolizes dreams and spirituality. Pisceans are compassionate, creative and deeply intuitive.",
    career: "Phù hợp với nghệ thuật, âm nhạc, tâm lý, y học, tâm linh.",
    love: "Trong tình yêu, Song Ngư lãng mạn, vị tha và yêu không điều kiện. Cần học cách bảo vệ bản thân.",
  },
];

// ----- 10 HÀNH TINH -----
export const PLANETS = [
  { vi: "Mặt Trời", en: "Sun", symbol: "☉", meaning: "Bản ngã, ý thức, cá tính, sức sống. Đại diện cho con người thật của bạn.",
    meaningEn: "Self, ego, consciousness, vitality. Represents your true self.",
    positive: ["Tự tin", "Sáng tạo", "Lãnh đạo", "Hào phóng"],
    negative: ["Kiêu ngạo", "Ích kỷ", "Thích kiểm soát"],
    body: "Tim, mắt, cột sống" },
  { vi: "Mặt Trăng", en: "Moon", symbol: "☽", meaning: "Cảm xúc, tiềm thức, thói quen, bản năng. Đại diện cho đời sống nội tâm.",
    meaningEn: "Emotions, subconscious, habits, instincts. Represents inner life.",
    positive: ["Nhạy cảm", "Trực giác", "Nuôi dưỡng", "Bảo vệ"],
    negative: ["Thất thường", "Ủy mị", "Phụ thuộc"],
    body: "Dạ dày, ngực, chất lỏng" },
  { vi: "Sao Thủy", en: "Mercury", symbol: "☿", meaning: "Giao tiếp, tư duy, học hỏi, thông tin. Đại diện cho cách bạn suy nghĩ và giao tiếp.",
    meaningEn: "Communication, thinking, learning, information. How you think and express.",
    positive: ["Thông minh", "Nhanh nhẹn", "Hài hước", "Tò mò"],
    negative: ["Hời hợt", "Lưỡng lự", "Nói nhiều"],
    body: "Hệ thần kinh, phổi, tay" },
  { vi: "Sao Kim", en: "Venus", symbol: "♀", meaning: "Tình yêu, sắc đẹp, giá trị, hưởng thụ. Đại diện cho cách bạn yêu và gu thẩm mỹ.",
    meaningEn: "Love, beauty, values, pleasure. How you love and your aesthetic.",
    positive: ["Quyến rũ", "Tinh tế", "Hào phóng", "Ấm áp"],
    negative: ["Hời hợt", "Chỉ hưởng thụ", "Phụ thuộc"],
    body: "Thận, cổ họng, da" },
  { vi: "Sao Hỏa", en: "Mars", symbol: "♂", meaning: "Năng lượng, hành động, tham vọng, dục vọng. Đại diện cho cách bạn hành động.",
    meaningEn: "Energy, action, ambition, desire. How you take action.",
    positive: ["Dũng cảm", "Quyết đoán", "Năng động", "Mạnh mẽ"],
    negative: ["Nóng nảy", "Hấp tấp", "Hung hăng"],
    body: "Cơ bắp, máu, bộ phận sinh dục" },
  { vi: "Sao Mộc", en: "Jupiter", symbol: "♃", meaning: "May mắn, mở rộng, triết lý, lạc quan. Đại diện cho sự may mắn và phát triển.",
    meaningEn: "Luck, expansion, philosophy, optimism. Represents fortune and growth.",
    positive: ["Lạc quan", "Hào phóng", "Thông thái", "Vui vẻ"],
    negative: ["Quá đà", "Thiếu tế nhị", "Xa rời thực tế"],
    body: "Gan, hông, đùi" },
  { vi: "Sao Thổ", en: "Saturn", symbol: "♄", meaning: "Kỷ luật, trách nhiệm, bài học, giới hạn. Đại diện cho những bài học cuộc đời.",
    meaningEn: "Discipline, responsibility, lessons, limitations. Life's teachers.",
    positive: ["Kỷ luật", "Kiên nhẫn", "Trách nhiệm", "Thực tế"],
    negative: ["Lạnh lùng", "Bi quan", "Khắc kỷ", "Chậm chạp"],
    body: "Xương, răng, đầu gối" },
  { vi: "Sao Thiên Vương", en: "Uranus", symbol: "♅", meaning: "Đột phá, đổi mới, nổi loạn, độc đáo. Đại diện cho sự thay đổi bất ngờ.",
    meaningEn: "Breakthrough, innovation, rebellion, uniqueness. Sudden changes.",
    positive: ["Sáng tạo", "Độc lập", "Tiến bộ", "Độc đáo"],
    negative: ["Nổi loạn", "Khó đoán", "Xa cách"],
    body: "Mắt cá chân, hệ thần kinh" },
  { vi: "Sao Hải Vương", en: "Neptune", symbol: "♆", meaning: "Giấc mơ, tâm linh, ảo tưởng, nghệ thuật. Đại diện cho thế giới tâm linh.",
    meaningEn: "Dreams, spirituality, illusion, art. The spiritual world.",
    positive: ["Trực giác", "Sáng tạo", "Nhân từ", "Tâm linh"],
    negative: ["Ảo tưởng", "Mơ hồ", "Lừa dối", "Trốn tránh"],
    body: "Bàn chân, hệ bạch huyết" },
  { vi: "Diêm Vương", en: "Pluto", symbol: "♇", meaning: "Biến đổi, quyền lực, tái sinh, chiều sâu. Đại diện cho sự chuyển hóa.",
    meaningEn: "Transformation, power, rebirth, depth. Metamorphosis.",
    positive: ["Sâu sắc", "Quyết tâm", "Mạnh mẽ", "Tái sinh"],
    negative: ["Cực đoan", "Thích kiểm soát", "Bí mật"],
    body: "Bộ phận sinh dục, trực tràng" },
];

// ----- 12 NHÀ -----
export const HOUSES = [
  { vi: "Nhà 1 — Bản thân", en: "1st House — Self",
    meaning: "Tính cách, ngoại hình, cách người khác nhìn nhận bạn, khởi đầu cuộc đời.",
    meaningEn: "Personality, appearance, how others see you, life's beginnings." },
  { vi: "Nhà 2 — Tài chính", en: "2nd House — Finance",
    meaning: "Tiền bạc, tài sản, giá trị bản thân, thu nhập, của cải vật chất.",
    meaningEn: "Money, possessions, self-worth, income, material wealth." },
  { vi: "Nhà 3 — Giao tiếp", en: "3rd House — Communication",
    meaning: "Giao tiếp, học tập, anh chị em, di chuyển, tư duy ngắn hạn.",
    meaningEn: "Communication, learning, siblings, short trips, short-term thinking." },
  { vi: "Nhà 4 — Gia đình", en: "4th House — Family",
    meaning: "Gia đình, nhà cửa, nguồn gốc, nội tâm, cuối đời.",
    meaningEn: "Family, home, roots, inner self, end of life." },
  { vi: "Nhà 5 — Sáng tạo", en: "5th House — Creativity",
    meaning: "Sáng tạo, tình yêu, con cái, giải trí, rủi ro, niềm vui.",
    meaningEn: "Creativity, romance, children, entertainment, risk, joy." },
  { vi: "Nhà 6 — Công việc", en: "6th House — Work",
    meaning: "Công việc hàng ngày, sức khỏe, thói quen, dịch vụ, đồng nghiệp.",
    meaningEn: "Daily work, health, routines, service, coworkers." },
  { vi: "Nhà 7 — Hôn nhân", en: "7th House — Partnership",
    meaning: "Hôn nhân, đối tác, hợp tác, quan hệ một-một, công khai thù địch.",
    meaningEn: "Marriage, partners, collaboration, one-on-one relationships." },
  { vi: "Nhà 8 — Biến đổi", en: "8th House — Transformation",
    meaning: "Biến đổi, tài sản chung, tâm lý, bí ẩn, chết và tái sinh.",
    meaningEn: "Transformation, shared resources, psychology, mystery, death and rebirth." },
  { vi: "Nhà 9 — Triết lý", en: "9th House — Philosophy",
    meaning: "Triết học, du lịch xa, giáo dục cao, tôn giáo, luật pháp, ý nghĩa cuộc sống.",
    meaningEn: "Philosophy, long journeys, higher education, religion, law, life meaning." },
  { vi: "Nhà 10 — Sự nghiệp", en: "10th House — Career",
    meaning: "Sự nghiệp, danh vọng, địa vị, mục tiêu cuộc đời, người mẹ/cha.",
    meaningEn: "Career, fame, status, life goals, mother/father figure." },
  { vi: "Nhà 11 — Bạn bè", en: "11th House — Friends",
    meaning: "Bạn bè, nhóm, hy vọng, ước mơ, mạng lưới xã hội, lý tưởng.",
    meaningEn: "Friends, groups, hopes, dreams, social network, ideals." },
  { vi: "Nhà 12 — Tâm linh", en: "12th House — Spirituality",
    meaning: "Tiềm thức, tâm linh, cô độc, bệnh viện, kẻ thù ngầm, nghiệp quả.",
    meaningEn: "Subconscious, spirituality, solitude, hospitals, hidden enemies, karma." },
];

// ----- ASPECT MEANINGS -----
export const ASPECTS = {
  conjunction: { vi: "Hợp", en: "Conjunction", angle: 0, orb: 8,
    meaning: "Hai hành tinh kết hợp năng lượng với nhau, tạo ra sức mạnh tập trung. Tốt hay xấu tùy thuộc vào bản chất các hành tinh.",
    meaningEn: "Two planets combine energies, creating focused power. Good or bad depends on the planets involved." },
  sextile: { vi: "Lục hợp", en: "Sextile", angle: 60, orb: 6,
    meaning: "Góc hài hòa, mang đến cơ hội và tài năng. Dễ dàng phát huy thế mạnh.",
    meaningEn: "Harmonious angle, brings opportunities and talents. Easy to leverage strengths." },
  square: { vi: "Hình vuông", en: "Square", angle: 90, orb: 8,
    meaning: "Góc xung khắc, tạo ra thách thức và xung đột. Đòi hỏi nỗ lực vượt qua.",
    meaningEn: "Challenging angle, creates obstacles and conflict. Requires effort to overcome." },
  trine: { vi: "Tam hợp", en: "Trine", angle: 120, orb: 8,
    meaning: "Góc hài hòa nhất, mang đến tài năng thiên bẩm và may mắn. Năng lượng chảy tự nhiên.",
    meaningEn: "Most harmonious angle, brings natural talent and luck. Energy flows naturally." },
  opposition: { vi: "Xung đối", en: "Opposition", angle: 180, orb: 8,
    meaning: "Góc đối lập, tạo ra căng thẳng và mâu thuẫn giữa hai lực. Cần tìm sự cân bằng.",
    meaningEn: "Opposing angle, creates tension and conflict between two forces. Need to find balance." },
};

// ----- ELEMENT MEANINGS -----
export const ELEMENTS = {
  "Lửa": { en: "Fire", meaning: "Nhiệt huyết, năng động, sáng tạo, dũng cảm. Người thuộc nhóm Lửa có đam mê và sức sống mạnh mẽ.",
    meaningEn: "Passionate, dynamic, creative, brave. Fire signs have strong passion and vitality." },
  "Đất": { en: "Earth", meaning: "Thực tế, ổn định, kiên nhẫn, chăm chỉ. Người thuộc nhóm Đất có nền tảng vững chắc.",
    meaningEn: "Practical, stable, patient, hardworking. Earth signs have solid foundations." },
  "Khí": { en: "Air", meaning: "Trí tuệ, giao tiếp, xã hội, sáng tạo. Người thuộc nhóm Khí có tư duy sắc sảo.",
    meaningEn: "Intellectual, communicative, social, creative. Air signs have sharp minds." },
  "Nước": { en: "Water", meaning: "Cảm xúc, trực giác, nhạy cảm, sâu sắc. Người thuộc nhóm Nước giàu cảm xúc.",
    meaningEn: "Emotional, intuitive, sensitive, deep. Water signs are emotionally rich." },
};
