-- Add Astrology fields to profiles table
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS noi_sinh TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS vi_do DOUBLE PRECISION DEFAULT 21.0285;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS kinh_do DOUBLE PRECISION DEFAULT 105.8542;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS chiem_tinh_report JSONB;
