UPDATE public.projects SET
  description='NOOI Forest — dự án hệ sinh thái du lịch – nghỉ dưỡng – kinh tế tái sinh tại Măng Đen (Kon Plông) và Đăk Rve (Kon Rẫy), tỉnh Quảng Ngãi. Pháp nhân triển khai là NOOI FOREST (công ty cổ phần, trụ sở Đăk Rve), thuê môi trường rừng từ BQL Rừng phòng hộ Kon Rẫy với diện tích 200–300 ha (thời hạn không quá 30 năm, chi trả tối thiểu 1% doanh thu/năm). Vốn điều lệ 10 tỷ đồng; NOOI Group (TNHH một thành viên, trụ sở Măng Đen) góp 25% bằng quyền sử dụng tài sản trí tuệ. Định hướng: phát triển Măng Đen thành hệ sinh thái du lịch, nghỉ dưỡng và kinh tế tái sinh có bản sắc riêng, khai thác hài hòa cảnh quan – khí hậu – tài nguyên bản địa; phục hồi tài nguyên, nâng cao giá trị đất đai và phát triển sinh kế bền vững cho cộng đồng địa phương.',
  location='Măng Đen (Kon Plông) & Đăk Rve (Kon Rẫy), Quảng Ngãi',
  highlights='[{"icon": "🛒", "title": "Trụ cột 1 — Thương mại · Dịch vụ · Du lịch", "desc": "Check-in săn mây, lưu trú sinh thái (homestay/bungalow), F&B bản địa, du lịch trải nghiệm, đặc sản — ưu tiên giai đoạn đầu để tạo dòng tiền sớm."}, {"icon": "🌿", "title": "Trụ cột 2 — Nông nghiệp rừng · Dược liệu", "desc": "Rau củ xứ lạnh, cây ăn quả, nông nghiệp dưới tán rừng, vùng dược liệu và chế biến — vùng nguyên liệu cho F&B và trung tâm chữa lành."}, {"icon": "🧘", "title": "Trụ cột 3 — Chữa lành · Phát triển bản thân", "desc": "Thiền, yoga, chánh niệm, dinh dưỡng, phục hồi lối sống; retreat chuyên đề cho doanh nghiệp — nhóm dịch vụ giá trị cao."}, {"icon": "♻️", "title": "Trụ cột 4 — Kinh tế tái sinh", "desc": "Biochar (than sinh học), giấm gỗ, nông nghiệp tái sinh, phục hồi hệ sinh thái; tiềm năng tín chỉ carbon (chưa tính vào dòng tiền cơ sở)."}, {"icon": "🧑‍💻", "title": "Trụ cột 5 — OPC Center (doanh nghiệp 1 người)", "desc": "Chuẩn hóa freelancer / KOL / hộ kinh doanh thành doanh nghiệp 1 người vận hành bài bản; mục tiêu 1.000 doanh nghiệp giai đoạn 1."}, {"icon": "⚖️", "title": "Ưu đãi & khung pháp lý", "desc": "Cả NOOI Group (Măng Đen) và NOOI FOREST (Đăk Rve) thuộc địa bàn ưu đãi: TNDN 10%/15 năm, miễn 4 năm, giảm 50% trong 9 năm; thuê môi trường rừng hợp pháp ≥1% doanh thu/năm."}]'::jsonb,
  timeline='[{"date": "Q4/2026 – Q2/2027", "title": "Giai đoạn 1 — Nền móng", "desc": "Thành lập NOOI Group (Măng Đen) và NOOI FOREST (Đăk Rve); điều lệ + thỏa thuận cổ đông; chọn đất 200–300 ha; đăng ký nhãn hiệu; góp vốn bằng quyền sử dụng IP.", "done": false}, {"date": "Q3/2027 – 2028", "title": "Giai đoạn 2 — Khởi chạy dòng tiền", "desc": "Ưu tiên Check-in & F&B; khởi động OPC Center (1.000 doanh nghiệp 1 người); hợp tác đối tác triển khai; hoàn tất đất và quy hoạch 1/500.", "done": false}, {"date": "2029", "title": "Giai đoạn 3 — Mở rộng", "desc": "Mở rộng 5 trụ cột; mở rộng cổ đông; triển khai ERP; chuẩn hóa quản trị.", "done": false}, {"date": "2030+", "title": "Giai đoạn 4 — Tăng trưởng", "desc": "Nhân rộng mô hình; nghiên cứu phương án vốn/IPO nếu phù hợp (đang tạm dừng, giữ cấu trúc chuẩn để tái kích hoạt).", "done": false}]'::jsonb,
  video_url=NULL,
  updated_at=now()
WHERE id='44b1faf9-5d03-4aee-8b5c-42bdfb41d8c7';
SELECT title, slug, location, left(description,70) AS desc_dau, jsonb_array_length(highlights) AS hl, jsonb_array_length(timeline) AS gd, video_url FROM public.projects;
